# Generated by Django 4.2 on 2025-08-11 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do CRP')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialização')),
                ('institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Avaliador',
                'verbose_name_plural': 'Perfis dos Avaliadores',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
