#!/bin/bash
# Script para configurar variáveis de ambiente no Railway
# Execute este script após o deploy inicial

echo "🚀 Configurando variáveis de ambiente para Railway..."

echo "As seguintes variáveis devem ser configuradas no painel do Railway:"
echo ""
echo "1. SECRET_KEY (obrigatório):"
echo "   Gere uma nova chave secreta segura"
echo "   Exemplo: django-insecure-sua-chave-super-secreta-aqui"
echo ""
echo "2. DEBUG (recomendado):"
echo "   false"
echo ""
echo "3. ALLOWED_HOSTS (obrigatório):"
echo "   *.railway.app,*.up.railway.app"
echo ""
echo "4. DATABASE_URL (automático):"
echo "   Configurado automaticamente pelo Railway quando adicionar PostgreSQL"
echo ""
echo "📋 Passos no Railway:"
echo "1. Acesse: https://railway.app/dashboard"
echo "2. Selecione seu projeto CareSense"
echo "3. Vá em Variables"
echo "4. Adicione as variáveis listadas acima"
echo "5. Adicione o serviço PostgreSQL"
echo "6. Faça redeploy do projeto"
echo ""
echo "🔧 Comandos após configurar as variáveis:"
echo "1. python manage.py migrate"
echo "2. python manage.py collectstatic --noinput"
echo "3. python manage.py createsuperuser"
