# Generated by Django 4.2.14 on 2025-08-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal_weekday', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Dia da semana')),
                ('temporal_day', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Data do mês')),
                ('temporal_month', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Mês')),
                ('temporal_year', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Ano')),
                ('temporal_hour', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Hora (±60 min)')),
                ('spatial_location', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Local (consultório/quarto)')),
                ('spatial_place', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Lugar (hospital/clínica)')),
                ('spatial_neighborhood', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Bairro/rua')),
                ('spatial_city', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Cidade')),
                ('spatial_state', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Estado')),
                ('memory_word1', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Palavra 1 (carro)')),
                ('memory_word2', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Palavra 2 (vaso)')),
                ('memory_word3', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Palavra 3 (tijolo)')),
                ('attention_calc1', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='100 - 7 = 93')),
                ('attention_calc2', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='93 - 7 = 86')),
                ('attention_calc3', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='86 - 7 = 79')),
                ('attention_calc4', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='79 - 7 = 72')),
                ('attention_calc5', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='72 - 7 = 65')),
                ('recall_word1', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Evocação palavra 1')),
                ('recall_word2', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Evocação palavra 2')),
                ('recall_word3', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Evocação palavra 3')),
                ('naming_object1', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Nomear relógio')),
                ('naming_object2', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Nomear caneta')),
                ('repetition_phrase', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Repetir: "Nem aqui, nem ali, nem lá"')),
                ('command_take', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Pegar folha com mão direita')),
                ('command_fold', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Dobrar ao meio')),
                ('command_put', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Colocar no chão')),
                ('written_command', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Ler e executar: "FECHE OS OLHOS"')),
                ('write_sentence', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Escrever frase (com verbo e sentido)')),
                ('copy_pentagons', models.IntegerField(choices=[(0, 'Incorreto'), (1, 'Correto')], default=0, verbose_name='Copiar pentágonos intersectados')),
                ('total_score', models.IntegerField(default=0, verbose_name='Pontuação Total (0-30)')),
                ('interpretation', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('MILD_IMPAIRMENT', 'Comprometimento Leve'), ('MODERATE_IMPAIRMENT', 'Comprometimento Moderado'), ('SEVERE_IMPAIRMENT', 'Comprometimento Grave'), ('REQUIRES_EVALUATION', 'Requer Avaliação Adicional')], max_length=25, verbose_name='Interpretação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meem_result', to='assessments.assessment', verbose_name='Avaliação')),
            ],
            options={
                'verbose_name': 'Resultado MEEM',
                'verbose_name_plural': 'Resultados MEEM',
            },
        ),
    ]
