# Generated by Django 4.2.14 on 2025-08-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_meemresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='meemresult',
            name='z_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Z-Score'),
        ),
    ]
