# Generated by Django 4.2.14 on 2025-08-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_meemresult_z_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockDrawingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_time', models.CharField(default='10:05', help_text='Formato HH:MM (ex: 10:05, 11:10)', max_length=10, verbose_name='Hora Solicitada')),
                ('circle_score', models.IntegerField(choices=[(0, 'Ausente ou gravemente distorcido'), (1, 'Presente mas ligeiramente distorcido'), (2, 'Círculo perfeito ou quase perfeito')], default=0, verbose_name='Pontuação do Círculo')),
                ('numbers_score', models.IntegerField(choices=[(0, 'Números ausentes ou completamente incorretos'), (1, 'Alguns números presentes mas com muitos erros'), (2, 'Números presentes mas com alguns erros de posição/sequência'), (3, 'Todos os números presentes com pequenos erros'), (4, 'Todos os 12 números corretos e bem posicionados')], default=0, verbose_name='Pontuação dos Números')),
                ('hands_score', models.IntegerField(choices=[(0, 'Ponteiros ausentes ou completamente incorretos'), (1, 'Apenas um ponteiro presente ou ambos incorretos'), (2, 'Ambos ponteiros presentes mas com hora incorreta'), (3, 'Ponteiros presentes, hora quase correta'), (4, 'Ambos ponteiros corretos indicando a hora exata')], default=0, verbose_name='Pontuação dos Ponteiros')),
                ('total_score', models.IntegerField(default=0, verbose_name='Pontuação Total')),
                ('z_score', models.FloatField(blank=True, null=True, verbose_name='Z-Score')),
                ('classification', models.CharField(blank=True, choices=[('NORMAL', 'Normal (>6 pontos)'), ('IMPAIRED', 'Comprometimento Cognitivo (≤6 pontos)')], max_length=10, verbose_name='Classificação')),
                ('observations', models.TextField(blank=True, help_text='Detalhes sobre o processo de execução, dificuldades observadas, etc.', verbose_name='Observações do Avaliador')),
                ('drawing_data', models.TextField(blank=True, help_text='Imagem do desenho em formato base64', verbose_name='Dados do Desenho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Duração (segundos)')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clock_drawing_result', to='assessments.assessment', verbose_name='Avaliação')),
            ],
            options={
                'verbose_name': 'Resultado do Teste do Relógio',
                'verbose_name_plural': 'Resultados do Teste do Relógio',
                'ordering': ['-created_at'],
            },
        ),
    ]
