# Generated by Django 4.2 on 2025-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_clockdrawingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='confidence_level',
            field=models.FloatField(default=0.0, help_text='Nível de confiança da avaliação baseado no número de testes completados', verbose_name='Nível de Confiança (%)'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='final_z_score',
            field=models.FloatField(blank=True, help_text='Z-Score final calculado com sistema de pesos por domínio cognitivo', null=True, verbose_name='Z-Score Final Ponderado'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_tests_completed',
            field=models.IntegerField(default=0, help_text='Número de testes neuropsicológicos completados nesta avaliação', verbose_name='Total de Testes Completados'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='final_risk_score',
            field=models.CharField(blank=True, choices=[('MINIMAL', 'Mínimo'), ('LOW', 'Baixo'), ('MODERATE', 'Moderado'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], max_length=10, null=True, verbose_name='Pontuação Final de Risco'),
        ),
    ]
