# Generated by Django 4.2 on 2025-08-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
