# Generated by Django 4.2 on 2025-08-14 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='education_years',
            field=models.IntegerField(blank=True, help_text='Campo legado, opcional. Não é mais utilizado para cálculos.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Anos de Estudo (legado)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='education_level',
            field=models.CharField(choices=[('NONE', 'Sem escolaridade'), ('FUNDAMENTAL', 'Fundamental'), ('MEDIO', 'Ensino Médio'), ('GRADUACAO', 'Graduação'), ('POSGRAD', 'Pós-graduação')], default='FUNDAMENTAL', help_text='Nível de escolaridade (ex.: Fundamental, Médio, Graduação)', max_length=20, verbose_name='Escolaridade'),
        ),
    ]
