# Generated by Django 4.2.14 on 2025-08-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_education_level_choices'),
        ('patients', '0003_patient_education_years_and_more'),
    ]

    operations = [
    ]
